[package]
name = "rbst"
version = "0.1.0"
edition = "2021"
description = "Self-balancing binary search trees"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
